### PR TITLE
Add support of EAP build (233.*)

### PR DESCRIPTION
**Pull request by pan93412**
## The Problem/Issue/Bug:

This plugin is incompatible with 2023.3 EAP.

## How this PR Solves the Problem:

Upgrade extension versions to EAP.

CleanShot 2023-10-05 at 14 37 35@2x

CleanShot 2023-10-05 at 14 51 56@2x

CleanShot 2023-10-05 at 14 52 24@2x

## Manual Testing Instructions:

Build integrated with #238, #239, #240, #241: 
[ddev-intellij-plugin-1.1.2-EAP.2.zip](https://github.com/php-perfect/ddev-intellij-plugin/files/12813162/ddev-intellij-plugin-1.1.2-EAP.2.zip)

### CODE REVIEW

**Comment by nico-loeber** [comment]
Hi @pan93412,

It's great to see you start to update the plugin for the next IntelliJ Release.
If you are interested, you could go one step further and think about an EAP Release workflow for the plugin.

Currently I release the new version of the plugin a few days after the new release of the IDE. I do not like to publish a stable version of the plugin compiled with a development/EAP snapshot of the IDE.
But it would be great to have a way to release EAP Versions of the plugin that are compatible with the EAP versions of the IDE.

Maybe you like to give this a try?

**Comment by nico-loeber** [comment]
Removing `until-build` would make it possible to install old versions of the plugin in current versions of the IDE which might not be compatible. I don't think this is a good idea.

And yes, I prepared the release workflow for eap and other builds but I never published one.

I didn't wanted to maintain a second branch with different dependencies and `form-` and `until-build`s.
If you have any idea on how to make this easily maintainable, please let me know.

**Comment by pan93412** [comment]
> Removing `until-build` would make it possible to install old versions of the plugin in current versions of the IDE which might not be compatible. I don't think this is a good idea.
> 
> And yes, I prepared the release workflow for eap and other builds but I never published one.
> 
> I didn't wanted to maintain a second branch with different dependencies and `form-` and `until-build`s. If you have any idea on how to make this easily maintainable, please let me know.

Maybe we can maintain the version in `gradle.properties` with:

```properties
version.idea.stable = IU-232.8660.185
version.ext.php.stable = 232.8660.185

version.idea.eap = 233.8264.8-EAP-SNAPSHOT
version.ext.php.eap = com.jetbrains.php:233.8264.9
```

And we pick the version by checking if `version` includes EAP:

```kotlin
fun versionByTag(component: String): String {
    val version = version.toString();
    val category = when {
        version.contains("eap") -> "eap"
        else -> "stable"
    };
    val key = "version.$component.$category";

    return project.properties[key]?.toString().or {
        throw Exception("$key is undefined.")
    }
}
```

```kotlin
intellij {
    type.set("IU")
    version.set(versionByTag("idea")) // https://www.jetbrains.com/de-de/idea/download/other.html
    plugins.add("com.intellij.database") // bundled
    plugins.add("org.jetbrains.plugins.terminal") // bundled
    plugins.add("com.jetbrains.plugins.webDeployment") // bundled
    plugins.add("org.jetbrains.plugins.remote-run") // bundled
    plugins.add("Docker") // bundled
    plugins.add("NodeJS") // bundled
    plugins.add("org.jetbrains.plugins.node-remote-interpreter") // bundled
    plugins.add("com.jetbrains.php:${versionByTag("ext.php")}") // https://plugins.jetbrains.com/plugin/6610-php/versions
    plugins.add("org.jetbrains.plugins.phpstorm-remote-interpreter:${versionByTag("ext.phpstorm-remote-interpreter")}") // https://plugins.jetbrains.com/plugin/7511-php-remote-interpreter/versions
    plugins.add("org.jetbrains.plugins.phpstorm-docker:${versionByTag("ext.phpstorm-docker")}") // https://plugins.jetbrains.com/plugin/8595-php-docker/versions
}
```

How do you think?

**Comment by nico-loeber** [comment]
This might work but is quite a lot of hidden magic.

I think the most straight forward solution is to have 2 maintained branches.
One "main" and one "eap" branch. Both branches are protected and you can create releases from both branches.
One the "main" branch `until-build` is the current IDE version. On the "eap" branch `until-build` is the current eap version of the IDE.
As soon as the EAP phase of the IDE is finished, the eap branch is merged into main and a new plugin release is created based on the non eap snapshot of the ide.

But if I rember right there is some problem with the `until-build` regarding eap versions, as it matches only stable versions... that's something we need to test.

Two maintained portected branches will add up complexity but... should work. What do you think?

**Comment by pan93412** [comment]
> This might work but is quite a lot of hidden magic.
> 
> I think the most straight forward solution is to have 2 maintained branches.
> One "main" and one "eap" branch. Both branches are protected and you can create releases from both branches.
> One the "main" branch `until-build` is the current IDE version. On the "eap" branch `until-build` is the current eap version of the IDE.
> As soon as the EAP phase of the IDE is finished, the eap branch is merged into main and a new plugin release is created based on the non eap snapshot of the ide.
> 
> But if I rember right there is some problem with the `until-build` regarding eap versions, as it matches only stable versions... that's something we need to test.
> 
> Two maintained portected branches will add up complexity but... should work. What do you think?

Seems great and reliable. Btw, the regex only matches strings like `-eap5` (digit only after -eap). Maybe you can tweak it.

**Comment by nico-loeber** [comment]
Okay, then let's give it a try.

https://github.com/php-perfect/ddev-intellij-plugin/blob/0c35ae70ba1cc4ddfa491f647acae9e30f22fb7d/.github/workflows/release.yml#L7

Do you mean this one?

**Comment by pan93412** [comment]
> Okay, then let's give it a try.
> 
> https://github.com/php-perfect/ddev-intellij-plugin/blob/0c35ae70ba1cc4ddfa491f647acae9e30f22fb7d/.github/workflows/release.yml#L7
> 
> Do you mean this one?

Hmm, no. I mean this one:

https://github.com/php-perfect/ddev-intellij-plugin/blob/0c35ae70ba1cc4ddfa491f647acae9e30f22fb7d/.github/workflows/publish-release.yml#L31

**Comment by pan93412** [comment]
> Okay, then let's give it a try.
> 
> https://github.com/php-perfect/ddev-intellij-plugin/blob/0c35ae70ba1cc4ddfa491f647acae9e30f22fb7d/.github/workflows/release.yml#L7
> 
> Do you mean this one?

Besides, this regex also has a significant issue: `/[0-9]+.[0-9]+.[0-9]+-eap*/` matches:

- `1.1.1-eap`
- `1.1.1-eapp`
- `1.1.1-eappp`

You should change it to `/[0-9]+.[0-9]+.[0-9]+-eap.*/`, which might be your expected behavior:

- `1.1.1-eap`
- `1.1.1-eap.1234`
- `1.1.1-eap-1234`

**Comment by nico-loeber** [comment]
Okay, if you like you can pull request it.
But I am not sure if this number is even needed... I think when working on the eap branch you would probably increase the patch level for the next version instead of the number behind the eap.

**Comment by pan93412** [comment]
> Okay, if you like you can pull request it. But I am not sure if this number is even needed... I think when working on the eap branch you would probably increase the patch level for the next version instead of the number behind the eap.

I prefer `/-eap.*/` so we can have the maximum flexibility of versioning `eap`.

**Comment by Schrank** [comment]
I'm only understanding a little of what you wrote, but if I can help to get this merged and finished, tell me! :-)

**Comment by nico-loeber** [comment]
I started working on 2023.3 support on a new branch under my control in a new pull request targeting the main branch, as now IU 233 is acailable as target for compilation: https://github.com/php-perfect/ddev-intellij-plugin/pull/270
I have merged yours @pan93412 so your contribution is included.

**Pull request merged**
